# ----------------------------------------------------------------------------
#
# Package             : rdma-core
# Source Repo         : https://github.com/linux-rdma/rdma-core
# Travis Job Link     : https://travis-ci.com/github/ddeka2910/rdma-core/builds/216899625
# Created travis.yml  : Yes
# Maintainer          : Debabrata Deka <ddeka2910@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: true

dist: xenial
arch:
  - amd64
  - ppc64le
language: c++

sudo: true

dist: xenial
arch:
  - amd64
  - ppc64le
language: c++
addons:
  apt:
     packages:
       - build-essential
       - cmake
       - gcc
       - libudev-dev
       - libnl-3-dev
       - libnl-route-3-dev
       - ninja-build
       - pkg-config
       - valgrind
       - python3-dev
       - cython3
       - python3-docutils
       - pandoc

script:
  - bash build.sh
